name: Decoding tests (testnets)
on:
  push:
    tags:
      - v.**
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: Sepolia is usually down but it worked, turn it on when possible
        # TODO: Mumbai is not working right now
        network: [ Fuji ]
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run tests
        env:
          SETH_NETWORK: ${{ matrix.network }}
          SETH_ROOT_PRIVATE_KEY: ${{ secrets.TESTNET_COMMON_KEYS }}
        run: |
          nix develop -c make root_private_key=$SETH_ROOT_PRIVATE_KEY network=$SETH_NETWORK test