name: Decoding tests (testnets)
on:
  push:
    tags:
      - v.**
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-decode-testnet
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: Sepolia is usually down but it worked, turn it on when possible
        # TODO: Mumbai is not working right now
        network: [ Fuji ]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run tests
        env:
          NETWORK: ${{ matrix.network }}
          ROOT_PRIVATE_KEY: ${{ secrets.TESTNET_COMMON_KEYS }}
        run: |
          nix develop -c make root_private_key=$ROOT_PRIVATE_KEY network=$NETWORK test